// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	model "go-clickhouse-migrator/internal/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// Migration is an autogenerated mock type for the Migration type
type Migration struct {
	mock.Mock
}

// GetQueryParams provides a mock function with given fields:
func (_m *Migration) GetQueryParams() model.MigrationQueryParams {
	ret := _m.Called()

	var r0 model.MigrationQueryParams
	if rf, ok := ret.Get(0).(func() model.MigrationQueryParams); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.MigrationQueryParams)
	}

	return r0
}

// NewMigration creates a new instance of Migration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMigration(t interface {
	mock.TestingT
	Cleanup(func())
}) *Migration {
	mock := &Migration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
